spring:
  application:
    name: dataprocessor
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/dataprocessor}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

# Custom configuration
app:
  data:
    path: ${DATAPATH:C:/var/log/applications/API/dataprocessing}

logging:
  level:
    com.example.dataprocessor: DEBUG
    org.springframework.web: DEBUG
